# Generated by Django 5.1.5 on 2025-04-19 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='Date and time when the object was created')),
                ('date_last_modified', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last modified')),
                ('type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4, verbose_name='Transaction Type')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('price_per_stock', models.PositiveIntegerField(verbose_name='Price')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_as_owner', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
