# Generated by Django 5.1.5 on 2025-04-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_stocks_quantity_alter_stocks_name_transactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_as_stock', to='trades.stocks', verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
