# Generated by Django 5.1.5 on 2025-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_transactions_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
