  services:
    web:
      build:
        context: ../../
        dockerfile: ./devops/prod/Dockerfile
      container_name: cg-backend
      image: cg-backend:latest
      command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - static_volume:/usr/src/app/staticfiles
        - media_volume:/usr/src/app/mediafiles
      expose:
        - 8000
      env_file:
        - ../../envs/.env
      depends_on:
        - db
    db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ../../envs/.env
    nginx:
      build: ./nginx
      volumes:
        - static_volume:/home/app/web/staticfiles
        - media_volume:/home/app/web/mediafiles
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      ports:
        - 1337:80
      depends_on:
        - web
    redis:
      image: redis
      expose:
        - 6379
    worker:
      build:
        context: ../../
        dockerfile: ./devops/prod/Dockerfile
      command: [ 'celery', '-A', 'config', 'worker', '-l', 'info' ,'-Q','HIGH_PRIORITY_Q,LOW_PRIORITY_Q,DEFAULT_Q']
      depends_on:
        - redis
    flower:
      image: mher/flower:0.9.7
      command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
      ports:
        - 5557:5555
      depends_on:
        - redis
  volumes:
    postgres_data:
    static_volume:
    media_volume: