# Generated by Django 5.1.5 on 2025-04-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
    ]
