# Generated by Django 5.1.5 on 2025-04-19 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0004_remove_user_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dues',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identifier',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Balance'),
        ),
    ]
